const data = {
    product: [
        {
            _id: '1',
            name:'iPhone 12 Pro Max',                  
            category:'smartphones',
            image:'https://images-na.ssl-images-amazon.com/images/I/71MHTD3uL4L._SL1500_.jpg',
            price:125900,
            barnd:'Apple',
            rating:5,
            numReviews:10,
            description: 'High quality',
        },
        {
            _id: '2',
            name:'one plus 9pro',
            category:'smartphones',
            image:'https://images-na.ssl-images-amazon.com/images/I/61YSMhOd5EL._SL1500_.jpg',
            price:54999,
            barnd:'oneplus',
            rating:4,
            numReviews:12,
            description: 'maxquality',
        },   {
            _id: '3',
            name:'Apple MacBook Pro',
            category:'Laptops',
            image:'https://images-na.ssl-images-amazon.com/images/I/71an9eiBxpL._SL1500_.jpg',
            price:117000,
            barnd:'Apple',
            rating:4,
            numReviews:10,
            description: 'High quality',
        },   {
            _id: '4',
            name:'Apple AirPods',
            category:'Airpods',
            image:'https://images-na.ssl-images-amazon.com/images/I/71IPFP9WJIL._SL1500_.jpg',
            price:16000,
            barnd:'Apple',
            rating:5,
            numReviews:10,
            description: 'High quality',
        },
        {
            _id: '5',
            name:'Oneplus buds',
            category:'Airpods',
            image:'https://images-na.ssl-images-amazon.com/images/I/51vwQzwM%2BZL._SL1500_.jpg',
            price:10020,
            barnd:'oneplus',
            rating:4.5,
            numReviews:10,
            description: 'High quality Production',
        },
        {
            _id: '6',
            name:'Apple Watch Series 6',
            category:'smart watch',
            image:'https://images-na.ssl-images-amazon.com/images/I/718qilkBKUL._SL1500_.jpg',
            price:50000,
            barnd:'Apple',
            rating:5,
            numReviews:10,
            description: 'High quality',
        },
        {
            _id: '7',
            name:'One plus smartwatch',
            category:'smart watch',
            image:'https://images-na.ssl-images-amazon.com/images/I/519mJ4pjfyL._SL1000_.jpg',
            price:15999,
            barnd:'oneplus',
            rating:5,
            numReviews:10,
            description: 'High quality',
        },
        {
            _id: '8',
            name:'DELL inspiron 5593',
            category:'Laptops',
            image:'https://images-na.ssl-images-amazon.com/images/I/61miE9bCwrL._SL1000_.jpg',
            price:92000,
            barnd:'Dell',
            rating:5,
            numReviews:10,
            description: 'High quality',
        }
   ]
}
export default data
